language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy"
install:
  - pip install -r test-requirements.txt
  - pip install -e .
script:
  - nosetests -q --with-coverage --cover-package=pycron
sudo: false
after_success:
  - coveralls
